---
# tasks file for rpi
- name: Log on which Linux distro Docker is going to be installed
  debug:
    msg: "The distro: {{ ansible_distribution|lower }}. The version name: {{ ansible_distribution_release }}. The family is: {{ ansible_os_family }}"

- name: Install docker requirements
  package:
    name:
      - python-pip-whl
      - python-setuptools
      - curl
      - gnupg-agent
      - ca-certificates
      - apt-transport-https
      - software-properties-common
    state: present

- name: install docker
  package:
    name:
      - docker.io
    state: present

- name: add pi user to docker group
  user:
    name: pi
    groups: docker
    append: yes
  become: true
